# Generated by Django 2.0.1 on 2021-07-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_catetypeentity_fruitentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catetypeentity',
            options={'ordering': ['order_num'], 'verbose_name': '水果分类', 'verbose_name_plural': '水果分类'},
        ),
    ]
