# Generated by Django 2.0.1 on 2021-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210722_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEntity',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='店号')),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('store_type', models.IntegerField(choices=[(0, '自营'), (1, '第三方')], db_column='type_', verbose_name='类型')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='城市')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='成立时间')),
                ('last_time', models.DateField(auto_now=True, verbose_name='最后变更时间')),
            ],
            options={
                'verbose_name': '水果店',
                'verbose_name_plural': '水果店',
                'db_table': 't_store',
            },
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='source',
            field=models.CharField(max_length=30, verbose_name='源产地'),
        ),
        migrations.AlterUniqueTogether(
            name='storeentity',
            unique_together={('name', 'city')},
        ),
    ]
