# Generated by Django 2.0.1 on 2021-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210725_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='47eff135da21410a9ed4ea0ae26aea61', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
    ]
