# Generated by Django 2.0.1 on 2021-07-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210725_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='store', verbose_name='LOGO', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='LOGO高'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='是否开业'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='商店介绍'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
