# Generated by Django 2.0.1 on 2021-08-07 12:06

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210806_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[mainapp.models.UserValidator.valid_phone], verbose_name='手机号'),
        ),
    ]
